/**
 * Regenerates every mark the site serves, from the repo-root `design/`.
 *
 * `design/armada-icon.svg` is itself generated: `make icon` builds it from
 * `design/armada-mark.svg`, the same geometry it compiles into the app's Icon
 * Composer bundle. So the chain is one mark end to end:
 *
 *   design/armada-mark.svg --make icon--> design/armada-icon.svg
 *                                           --pnpm icons--> public/*
 *
 * Nothing here transcribes a coordinate. Cupertino once hand-copied its marks out
 * of a design directory and the site served an earlier direction of the mark than
 * the app shipped. Run `pnpm icons` after `make icon` rather than moving files.
 *
 * Every output is committed (as LFS for the PNGs; see .gitattributes), so a
 * checkout builds without running this.
 */
import { readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import sharp from "sharp";

import { SOCIAL_CARD } from "../src/config.ts";
import { composeCard } from "./social-card.mjs";

const here = dirname(fileURLToPath(import.meta.url));
const pub = join(here, "..", "public");
const design = join(here, "..", "..", "..", "design");

/** Loud on a missing source: a silent skip here ships a stale mark. */
const source = async (name) => {
  try {
    return await readFile(join(design, name), "utf8");
  } catch {
    throw new Error(
      `design/${name} is missing. It is generated by \`make icon\` at the repo root; run that first.`,
    );
  }
};

/**
 * Throws rather than passing the artwork through unchanged, so a change to what
 * `make icon` emits surfaces here instead of silently producing a wrong icon.
 */
const replaceOnce = (text, find, replacement, what) => {
  if (!text.includes(find)) throw new Error(`${what}: expected to find ${find}`);
  return text.replace(find, replacement);
};

const png = async (svg, out, size) => {
  const buf = await sharp(Buffer.from(svg), { density: 400 }).resize(size, size).png().toBuffer();
  await writeFile(join(pub, out), buf);
  console.log(`  ${out}  ${size}×${size}`);
};

console.log("icons →");

const icon = await source("armada-icon.svg");
const halo = await source("armada-menubar-active-halo.svg");

// Served as-is: /favicon.svg is linked by every page, /app-icon.svg is what every
// <Logo> renders, and the halo glyph is the real menu bar image in the hero's
// glance diagram (the state "a session wants you").
await writeFile(join(pub, "app-icon.svg"), icon);
await writeFile(join(pub, "favicon.svg"), icon);
await writeFile(join(pub, "menubar-glyph-halo.svg"), halo);
console.log("  app-icon.svg, favicon.svg, menubar-glyph-halo.svg  copied from design/");

await png(icon, "favicon-32.png", 32);

// iOS applies its own mask to the touch icon, so the plate is squared first;
// otherwise the corner radius is applied twice and the artwork reads pinched.
// Armada's waves bleed past the plate on purpose, and `make icon` clips them to
// the squircle for the web, so BOTH come back off here: the clip on the artwork
// and the radius on the plate rect. Removing only the clip (as the siblings do)
// would leave rounded top corners over square bottom ones, and iOS paints
// transparent corners black.
await png(
  replaceOnce(
    replaceOnce(icon, ' clip-path="url(#c)"', "", "apple-touch-icon clip"),
    ' rx="230" fill="url(#appshot-plate)"',
    ' fill="url(#appshot-plate)"',
    "apple-touch-icon plate radius",
  ),
  "apple-touch-icon.png",
  180,
);

// The Stripe product image, shown beside the line item on the hosted checkout.
// Stripe stores the URL and fetches it rather than taking an upload, so once the
// live product's `images` points here, the checkout's mark follows a site deploy
// and the payment link is never touched. Renaming or deleting this file will then
// break a page nothing in this repo builds. 512 is generous for a thumbnail, and
// the plate keeps its own corner radius: Stripe rounds the container far less
// than the squircle does, so squaring it would show as a crop.
await png(icon, "product-image.png", 512);

// The OG card: what a link to the site looks like on X, Slack and iMessage. The
// words come from src/config.ts, because they are a claim about the product and
// this file has no business being the authority on one.
//
// Rasterised at density 200 for clean edges, then resized back down: without the
// resize the PNG comes out 3333×1750, while Layout.astro declares og:image:width
// and height as 1200×630 from the same SOCIAL_CARD.
const card = composeCard(icon, JSON.parse(await source("colors.json")), SOCIAL_CARD);
await writeFile(
  join(pub, "og-image.png"),
  await sharp(Buffer.from(card), { density: 200 })
    .resize(SOCIAL_CARD.width, SOCIAL_CARD.height)
    .png({ palette: true })
    .toBuffer(),
);
console.log(`  og-image.png  ${SOCIAL_CARD.width}×${SOCIAL_CARD.height}`);
